"use client";

import { useState } from "react";
import Link from "next/link";

type View = "Dashboard" | "Explore instruments" | "My instruments" | "Activity" | "Eligibility";
type Profile = "pending" | "eligible" | "restricted";
const NAV: View[] = ["Dashboard", "Explore instruments", "My instruments", "Activity", "Eligibility"];
const ASSETS = [
  { id: "SMPL-ROY", name: "Northern royalty", type: "Royalty stream", resource: "Oil & gas", place: "Arctic basin", state: "Sample instrument", image: "/img/geom-hero-photo.jpg", description: "A defined share of an operator's revenue, represented by a permissioned instrument.", units: "1,000,000", right: "Pro-rata interest in the defined royalty stream. No ownership of the underlying licence or GEOM Foundation." },
  { id: "SMPL-MIN", name: "Critical minerals", type: "Offtake-linked instrument", resource: "Minerals", place: "Northern mineral belt", state: "Concept stage", image: "/img/geom-chapter-photo.jpg", description: "A concept for a resource instrument linked to specified mineral offtake rights.", units: "Not defined", right: "Rights would be defined by final issuer documents. No allocation or instrument exists." },
  { id: "SMPL-ENE", name: "Energy infrastructure", type: "Project participation", resource: "Energy", place: "Northern energy corridor", state: "Concept stage", image: "/img/bg-strata.webp", description: "A concept for participation in a separately structured energy infrastructure project.", units: "Not defined", right: "Participation terms would depend on the issuer's final legal structure. No allocation or instrument exists." },
] as const;
type Asset = typeof ASSETS[number];

export default function HolderExperience() {
  const [view, setView] = useState<View>("Dashboard");
  const [connected, setConnected] = useState(true);
  const [profile, setProfile] = useState<Profile>("pending");
  const [selected, setSelected] = useState<Asset | null>(null);
  const [tab, setTab] = useState("Overview");
  const [filter, setFilter] = useState("All resources");
  const [requested, setRequested] = useState(false);
  const [notice, setNotice] = useState("");
  const [statement, setStatement] = useState(false);

  function navigate(next: View) { setView(next); setSelected(null); setNotice(""); setStatement(false); }
  function inspect(asset: Asset) { setSelected(asset); setTab("Overview"); setNotice(""); }
  function reset() { setConnected(true); setProfile("pending"); setRequested(false); setSelected(null); setView("Dashboard"); setNotice(""); setStatement(false); }
  const status = !connected ? "Wallet disconnected" : profile === "eligible" ? "Sample checks complete" : profile === "restricted" ? "Action required" : "Verification needed";

  function cards() {
    return <div className="hp-assets">{ASSETS.filter(a => filter === "All resources" || a.resource === filter).map((a, i) => <button className="hp-asset" key={a.id} onClick={() => inspect(a)}>
      <div className="hp-asset-image" style={{ backgroundImage: `linear-gradient(180deg, transparent, rgba(12,21,25,.45)), url('${a.image}')` }}><span>{a.resource}</span><b>0{i + 1} ↗</b></div>
      <div className="hp-asset-body"><div className="hp-kicker">{a.id} <span>{a.state}</span></div><h3>{a.name}</h3><p>{a.type} · {a.place}</p><div className="hp-card-foot"><span>View instrument</span><span>↗</span></div></div>
    </button>)}</div>;
  }

  return <div className="hp">
    <aside className="hp-sidebar">
      <Link href="/" className="hp-logo">
        {/* eslint-disable-next-line @next/next/no-img-element -- existing static brand asset */}
        <img src="/brand/geom-logo-light.svg" alt="GEOM" />
      </Link>
      <div className="hp-workspace"><span className="hp-kicker">TOKENIZATION ENGINE</span><strong>Holder workspace</strong><span className="hp-preview">Design preview</span></div>
      <nav aria-label="Holder workspace">{NAV.map((n, i) => <button key={n} onClick={() => navigate(n)} aria-current={!selected && view === n ? "page" : undefined} className={!selected && view === n ? "active" : ""}><span className="hp-nav-icon" aria-hidden="true">{["◫", "◈", "▤", "↗", "◎"][i]}</span>{n}{n === "My instruments" && <small>01</small>}</button>)}</nav>
      <div className="hp-side-bottom"><div className="hp-network"><i /> Solana · Token-2022<span>Proposed instrument standard</span></div><Link href="/app?m=oracle">Open intelligence app ↗</Link><Link href="/engine">Issuer console ↗</Link><button onClick={reset}>Reset demo ↺</button></div>
    </aside>
    <div className="hp-main">
      <header className="hp-top"><div>Workspace <span>/</span> <strong>{selected ? selected.name : view}</strong></div><button className="hp-wallet" onClick={() => { setConnected(!connected); setNotice(""); }}><i className={connected ? "on" : ""} />{connected ? "Demo wallet · 7xKq…Ma1P" : "Connect demo wallet"}<span>{connected ? "Disconnect" : "→"}</span></button></header>
      <div className="hp-demo"><span>DEMO MODE</span> Fictional instruments and balances. No wallet signature, transaction or offer.<span className="hp-demo-right">TEAM PREVIEW / 01</span></div>
      <main className="hp-content">
        {selected ? <>
          <button className="hp-back" onClick={() => { setSelected(null); setNotice(""); }}>← Back to {view.toLowerCase()}</button>
          <div className="hp-detail-hero" style={{ backgroundImage: `linear-gradient(90deg, #101c22 5%, rgba(12,21,25,.4)), url('${selected.image}')` }}><span className="hp-kicker">{selected.resource} / {selected.id} / ILLUSTRATIVE</span><h1>{selected.name}</h1><p>{selected.description}</p><span className="hp-pill">{selected.type}</span></div>
          <div className="hp-detail-layout"><section className="hp-panel"><div className="hp-tabs" role="tablist" aria-label="Instrument information">{["Overview", "Evidence", "Terms"].map(t => <button key={t} role="tab" aria-selected={tab === t} onClick={() => setTab(t)}>{t}</button>)}</div>
            <div className="hp-tab-content" role="tabpanel" aria-label={tab}>{tab === "Overview" ? <><span className="hp-kicker">WHAT THE INSTRUMENT REPRESENTS</span><h2>A defined right. A separate asset.</h2><p>{selected.right}</p><dl className="hp-facts"><div><dt>Issuer</dt><dd>Sample Operator SPV Ltd (fictional)</dd></div><div><dt>Instrument standard</dt><dd>Solana Token-2022</dd></div><div><dt>Illustrative supply</dt><dd>{selected.units}</dd></div><div><dt>Transferability</dt><dd>Permissioned, subject to instrument rules</dd></div><div><dt>Underlying asset</dt><dd>Fictional project, no partner terms agreed</dd></div></dl></> : tab === "Evidence" ? <><span className="hp-kicker">DOCUMENTS & PUBLICATION RECORD</span><h2>Read the ground first.</h2><p>These document slots show what a holder would review. No documents for this fictional instrument have been signed or anchored.</p>{["Issuer statement", "Licence reference", "Independent resource report", "Instrument attestation"].map(t => <div className="hp-document" key={t}><span>▤ &nbsp; {t}</span><span>Not supplied</span></div>)}<Link className="hp-text-link" href="/app?m=oracle">Explore the live GEOM dataset oracle ↗</Link><p className="hp-fine">The oracle records integrity and publication time, not resource accuracy. Its live dataset anchors do not validate this sample instrument.</p></> : <><span className="hp-kicker">ILLUSTRATIVE CONDITIONS</span><h2>Know the boundaries.</h2>{["Instrument eligibility is separate from holding GEOM.", "Issuer-defined identity, jurisdiction and investor-class requirements apply.", "Transfers may be limited by holding periods, holder caps and recipient eligibility.", "Any distribution depends on the instrument terms and underlying statement; it is not a guaranteed return.", "No subscription, custody or settlement service is connected to this preview."].map((t, i) => <p className="hp-term" key={t}><span>0{i + 1}</span>{t}</p>)}</>}</div>
          </section><aside className="hp-panel hp-access"><span className="hp-kicker">YOUR ACCESS</span><h2>{selected.id !== "SMPL-ROY" ? "Under development" : status}</h2><p>{selected.id !== "SMPL-ROY" ? "This concept has no defined offering terms. Explore its structure and return as the design develops." : "Review your eligibility before proceeding to the issuer's instrument process."}</p><div className="hp-access-row"><span>GEOM balance</span><strong>{connected ? "25,000 GEOM" : "Connect demo wallet"}</strong></div><div className="hp-access-row"><span>Instrument approval</span><strong>{profile === "eligible" && connected ? "Sample only" : "Not approved"}</strong></div>{selected.id === "SMPL-ROY" && <button className="hp-primary" onClick={() => { if (!connected) { setConnected(true); } else if (profile !== "eligible") { navigate("Eligibility"); } else { setRequested(true); setNotice("Demo review request recorded locally. No application was submitted and no units were allocated."); } }}>{!connected ? "Connect demo wallet" : profile === "eligible" ? requested ? "Demo review requested ✓" : "Simulate issuer review request →" : "Review eligibility →"}</button>}<p className="hp-fine">Holding GEOM does not confer an interest in this instrument or its distributions.</p></aside></div>
        </> : <>
          <div className="hp-page-heading"><div><span className="hp-kicker">YOUR RESOURCE WORKSPACE</span><h1>{view === "Dashboard" ? "A closer view of real assets." : view}</h1><p>{view === "Dashboard" ? "Explore the instruments. Understand the rights. Follow the evidence." : view === "Explore instruments" ? "From the physical asset to the rights it represents. All examples are fictional." : view === "My instruments" ? "Your instrument register, separate from your GEOM balance." : view === "Eligibility" ? "A clear path from your wallet to instrument-specific access." : "Statements, access checks and instrument events in one place."}</p></div><span className="hp-date">HOLDER PREVIEW<br />05 SEP 2026</span></div>
          {view === "Dashboard" && <>
            <div className="hp-stats"><div><span className="hp-kicker">GEOM BALANCE · SAMPLE</span><strong>{connected ? "25,000" : "—"}<small> GEOM</small></strong><span>Separate from resource instruments</span></div><div><span className="hp-kicker">INSTRUMENT HOLDINGS · SAMPLE</span><strong>{connected ? "01" : "—"}<small> instrument</small></strong><button onClick={() => navigate("My instruments")}>View your register ↗</button></div><div><span className="hp-kicker">ACCESS STATUS</span><strong className="hp-stat-status">{status}</strong><button onClick={() => navigate("Eligibility")}>Review your eligibility ↗</button></div></div>
            <div className="hp-feature"><div className="hp-feature-copy"><span className="hp-kicker">01 / THE HOLDER JOURNEY</span><h2>From the resource.<br />To your register.</h2><p>See how a permissioned royalty instrument could look in your workspace, from its underlying rights to a recorded distribution.</p><button className="hp-primary" onClick={() => inspect(ASSETS[0])}>Explore sample instrument <span>↗</span></button></div><div className="hp-feature-caption"><span>ARCTIC RESOURCE LANDSCAPE</span><span>Illustrative instrument / SMPL-ROY</span></div></div>
            <div className="hp-section-heading"><h2>Explore the instrument layer</h2><button onClick={() => { setFilter("All resources"); navigate("Explore instruments"); }}>View all instruments ↗</button></div>{cards()}
          </>}
          {view === "Explore instruments" && <><div className="hp-filters" aria-label="Resource filters">{["All resources", "Oil & gas", "Minerals", "Energy"].map(f => <button key={f} aria-pressed={filter === f} onClick={() => setFilter(f)}>{f}</button>)}</div>{cards()}<div className="hp-context"><span>◎</span><div><h3>Evidence before access.</h3><p>Each instrument has its own issuer, rights and requirements. GEOM ownership alone does not establish eligibility.</p></div></div></>}
          {view === "Eligibility" && <section className="hp-panel hp-eligibility"><div><span className="hp-kicker">SMPL-ROY / SAMPLE ACCESS PROFILE</span><h2>{status}</h2><p>This walkthrough uses preset outcomes to show the holder experience. No personal information is collected and no real verification runs.</p><label className="hp-select-label">Demo scenario<select value={profile} onChange={e => { setProfile(e.target.value as Profile); setNotice(""); }}><option value="pending">Verification pending</option><option value="eligible">Sample checks complete</option><option value="restricted">Restricted profile</option></select></label></div><div className="hp-checklist">{["Wallet connected", "Identity credential", "Permitted jurisdiction", "Investor classification", "Instrument review"].map((s, i) => <div key={s}><span className="hp-check-number">0{i + 1}</span><div><strong>{s}</strong><p>{i === 0 ? "Sample session only. No wallet extension is accessed." : i === 4 ? "Issuer documents and approval are still required." : "Instrument-specific checks by an approved provider."}</p></div><span className="hp-check-status">{!connected ? "Waiting" : i === 0 ? "Demo connected" : i === 4 ? "Not submitted" : profile === "eligible" ? "Sample pass" : profile === "restricted" && i === 2 ? "Restricted" : "Pending"}</span></div>)}</div><button className="hp-primary" onClick={() => { if (!connected) setConnected(true); else if (profile === "restricted") setNotice("This sample profile cannot proceed. The issuer would need to resolve the restriction; holding GEOM does not override it."); else if (profile === "pending") { setProfile("eligible"); setNotice("Sample checks marked complete for the demo. This is not a real eligibility decision."); } else inspect(ASSETS[0]); }}>{!connected ? "Connect demo wallet →" : profile === "restricted" ? "Explain restriction →" : profile === "pending" ? "Simulate completed checks →" : "Return to sample instrument →"}</button></section>}
          {view === "My instruments" && (!connected ? <div className="hp-panel hp-empty"><h2>Open your sample register.</h2><p>Connect the demo wallet to view fictional holdings.</p><button className="hp-primary" onClick={() => setConnected(true)}>Connect demo wallet →</button></div> : <><div className="hp-context"><span>◈</span><div><h3>Instrument holdings are separate from GEOM.</h3><p>This register contains preloaded sample units. Completing demo checks does not acquire or issue an instrument.</p></div></div><section className="hp-panel hp-holding"><div><span className="hp-kicker">SMPL-ROY / SAMPLE HOLDING</span><h2>Northern royalty</h2><p>Royalty stream · Sample Operator SPV Ltd</p></div><div><span className="hp-kicker">UNITS HELD</span><strong>12,000</strong><span>1.2% of illustrative supply</span></div><button className="hp-secondary" onClick={() => inspect(ASSETS[0])}>Instrument details ↗</button></section><div className="hp-section-heading"><h2>Distribution record</h2><span>ILLUSTRATIVE · NO FUNDS MOVED</span></div><section className="hp-panel hp-distribution"><div><span className="hp-kicker">AUGUST 2026 STATEMENT</span><h2>368.28 <small>USDC</small></h2><p>Sample recorded amount for 12,000 units.</p></div><span className="hp-pill">Sample record</span><button className="hp-secondary" aria-expanded={statement} onClick={() => setStatement(!statement)}>{statement ? "Close statement ↑" : "View calculation ↓"}</button></section>{statement && <section className="hp-panel hp-calculation"><h3>How this example is calculated</h3><dl className="hp-facts">{[["Sample royalty amount", "31,000.00 USDC"], ["Illustrative administration holdback (1%)", "310.00 USDC"], ["Distributable amount", "30,690.00 USDC"], ["Total sample units", "1,000,000"], ["Amount per unit", "0.03069 USDC"], ["Your 12,000 sample units", "368.28 USDC"]].map(([k, v]) => <div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><p className="hp-fine">Fictional statement, not attested. This example is not a forecast or an entitlement for GEOM holders.</p></section>}</>)}
          {view === "Activity" && <section className="hp-panel hp-activity">{(connected ? [...(requested ? [["Just now", "Demo issuer review requested", "Local interaction only. No submission or allocation."]] : []), ["01 SEP 2026", "Sample distribution recorded", "SMPL-ROY · 368.28 USDC · no funds moved"], ["31 AUG 2026", "Sample statement added", "August royalty statement · fictional, not attested"], ["15 AUG 2026", "Sample register opened", "12,000 preloaded units · no on-chain instrument"]] : []).map(([date, title, desc]) => <div key={title}><span className="hp-kicker">{date}</span><div><h3>{title}</h3><p>{desc}</p></div><span>↗</span></div>)}{!connected && <p>Connect the demo wallet to view sample activity.</p>}</section>}
        </>}
        {notice && <div className="hp-notice" role="status">{notice}</div>}
        <footer className="hp-footer"><span>GEOM / REAL ASSETS FROM THE FAR NORTH</span><p>Design preview. Informational only, not investment advice. No issuance, custody, trading or settlement is available here.</p></footer>
      </main>
    </div>
  </div>;
}
